### ISSUE TITLE
Комментарии к заявке

### ISSUE THREAD

**Issue by aakuptsov** [kykazabra/FAN-performance-monitoring#1]
1. Необходимо создать файл с заявкой в соответствии с требованиями (см. группу в VK).

**Comment by kykazabra** [comment]
Спасибо, добавил отдельный файл в формате .md, так же информация продублирована во вкладке Wiki.

**Comment by aakuptsov** [comment]
Пожалуйста, открой issue и не закрывай до защиты :)

**Comment by aakuptsov** [comment]
Также, пожалуйста, переименуй файл в соответствии с требованиями и добавь в него свои контакты (почту, ссылку на VK).

**Comment by aakuptsov** [comment]
1. Опиши, пожалуйста, процедуру тестирования продукта при разработке.

2. Как можно на защите в Лицее убедиться в том, что продукт работает? Что для этого будет нужно сделать? Какое нужно будет оборудование?

**Comment by kykazabra** [comment]
Спасибо, постарался учесть все замечания. Добавил необходимые файлы, а имеющиеся переименовал в соответствии с требованиями

**Comment by aakuptsov** [comment]
Зачёт.
