### ISSUE TITLE
Комментарии к пользовательским сценариям

### ISSUE THREAD

**Issue by aakuptsov** [kykazabra/FAN-performance-monitoring#2]
1. На 21 апреля пользовательские сценарии отсутствуют.

2. Скрипт (sCript) в файле тестирования не может считаться сценариями.

**Comment by kykazabra** [comment]
Извиняюсь, не до конца ознакомился с необходимой документацией касательно формата пользовательских сценариев. Создал файл ailitvin_user_scripts.md с возможными пользовательскими сценариями.

**Comment by aakuptsov** [comment]
ЗАЧЁТ
